const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { calculateFleet, transitionPlan, frameDifference, validateAnswer, localAnswer, companionProfile, conversation, proactiveDecision } = require('../src/core.cjs');
const { openStore } = require('../src/store.cjs');
const { analyze } = require('../src/provider.cjs');

async function check() {
  const local = path.resolve(__dirname, '../.local'); fs.mkdirSync(local, { recursive: true });
  const directory = fs.mkdtempSync(path.join(local, 'check-'));
  let store;
  try {
    const input = { demand: 2, cycle: 10, slots: 1, perSlot: 50 };
    assert.equal(calculateFleet(input).ships, 1);
    assert.equal(calculateFleet({ ...input, demand: 11 }).ships, 3);
    assert.equal(calculateFleet({ ...input, demand: 0 }).ships, 0);
    assert.equal(calculateFleet({ demand: .3, cycle: .1, slots: 1, perSlot: .03 }).ships, 1);
    assert.equal(calculateFleet({ ...input, production: 1 }).productionShortfall, true);
    assert.equal(calculateFleet({ ...input, production: '' }).production, null);
    for (const demand of ['', ' ', [], false, null, -1, Infinity]) assert.throws(() => calculateFleet({ ...input, demand }));
    for (const slots of [0, 1.5, 101]) assert.throws(() => calculateFleet({ ...input, slots }));
    assert.throws(() => calculateFleet({ ...input, cycle: 0 }));
    assert.throws(() => calculateFleet({ ...input, demand: 1e308, cycle: 1e308 }));
    assert.equal(transitionPlan('proposed', 'accepted'), 'accepted');
    assert.throws(() => transitionPlan('accepted', 'resolved'));
    assert.equal(transitionPlan('applied', 'resolved'), 'resolved');
    assert.equal(frameDifference([0, 255], [0, 255]), 0);
    assert.equal(frameDifference([0], [255]), 1);
    const evidence = [{ id: 'frame-a', world_id: 'world-a' }];
    const valid = { summary: '결론', should_speak: true, event_type: 'help', event_key: '홉:공급부족', focus_busy: false, goal_related: true, facts: [{ text: '홉 재고', evidence_id: 'frame-a' }], hypotheses: ['운송 확인 필요'], missing_information: ['소비량'], suggestions: ['항로 확인'], memory_proposals: [], next_action: '화면 확인', annotations: [{ evidence_id: 'frame-a', x: .1, y: .2, width: .2, height: .3, label: '<script>literal</script>' }] };
    assert.equal(validateAnswer(valid, evidence).annotations[0].label, '<script>literal</script>');
    assert.throws(() => validateAnswer({ ...valid, facts: [{ text: '다른 월드', evidence_id: 'frame-b' }] }, evidence));
    assert.throws(() => validateAnswer({ ...valid, annotations: [{ ...valid.annotations[0], x: .9 }] }, evidence));
    assert.throws(() => validateAnswer({ ...valid, annotations: [{ ...valid.annotations[0], width: NaN }] }, evidence));
    assert.throws(() => validateAnswer({ ...valid, should_speak: 'yes' }, evidence));
    assert.throws(() => validateAnswer({ ...valid, event_type: 'victory!' }, evidence));
    const now = Date.now(), decision = { mode: 'together', goal: '맥주 공급', records: [], now, evidence: [{ id: 'frame-a', source: 'window', payload: { capturedAt: new Date(now - 1000).toISOString() } }] };
    assert.equal(proactiveDecision(valid, decision), null);
    assert.equal(proactiveDecision(valid, { ...decision, mode: 'quiet' }), 'quiet-mode');
    assert.equal(proactiveDecision({ ...valid, should_speak: false }, decision), 'nothing-new');
    assert.equal(proactiveDecision({ ...valid, focus_busy: true }, decision), 'focused-play');
    assert.equal(proactiveDecision(valid, { ...decision, sampleStable: false }), 'scene-changed');
    assert.equal(proactiveDecision(valid, { ...decision, status: 'deferred' }), 'inactive-plan');
    assert.equal(proactiveDecision(valid, { ...decision, evidence: [{ ...decision.evidence[0], source: 'video' }] }), 'no-current-evidence');
    assert.equal(proactiveDecision(valid, { ...decision, evidence: [{ ...decision.evidence[0], payload: { capturedAt: new Date(now - 20000).toISOString() } }] }), 'no-current-evidence');
    assert.equal(proactiveDecision({ ...valid, facts: [{ text: '과거 화면', evidence_id: 'old-frame' }] }, decision), 'no-current-evidence');
    assert.equal(proactiveDecision({ ...valid, event_type: 'reaction' }, { ...decision, mode: 'watch' }), 'outside-watch');
    const prior = (age, payload) => ({ id: String(age), kind: 'answer', created_at: new Date(now - age).toISOString(), payload });
    assert.equal(proactiveDecision(valid, { ...decision, records: [prior(1000, { automatic: false, summary: '대화' })] }), 'cooldown');
    assert.equal(proactiveDecision(valid, { ...decision, records: [prior(90000, { automatic: true, delivered: true, event_key: valid.event_key })] }), 'duplicate');
    assert.equal(proactiveDecision(valid, { ...decision, records: [90000, 180000, 270000].map(age => prior(age, { automatic: true, delivered: true })) }), 'frequency-limit');
    assert.equal(companionProfile({ name: '두리', style: 'calm', tone: 'casual', preferences: '힌트 먼저' }).name, '두리');
    assert.throws(() => companionProfile({ name: '', style: 'calm', tone: 'casual' }));
    assert.throws(() => companionProfile({ name: '두리', style: 'unknown', tone: 'casual' }));
    const recent = [prior(1000, { automatic: true, delivered: false, summary: '침묵 후보' }), prior(2000, { automatic: true, delivered: true, summary: '좋았어!' }), prior(3000, { question: '힌트만 줘', summary: '여기부터 볼까?' })];
    assert.deepEqual(conversation(recent).map(r => r.reply), ['여기부터 볼까?', '좋았어!']);
    assert.equal(conversation(recent)[1].question, null);

    store = openStore(directory);
    const a = store.create('홉 월드', 'anno1800', '맥주 공급');
    const b = store.create('다른 월드', 'factorio', '철판 공급');
    const generic = store.create('새로운 모험', '어떤 게임이든', '');
    assert.equal(generic.game, '어떤 게임이든');
    assert.equal(generic.state.scenario, null);
    assert.equal(store.records(generic.id).length, 0);
    const oldConversation = store.add(generic.id, 'answer', 'model', { question: '오늘은 탐험만 하자', summary: '좋아, 천천히 둘러보자.' });
    store.add(generic.id, 'answer', 'model', { automatic: true, delivered: false, summary: '미전달 후보' });
    for (let i = 0; i < 110; i++) store.add(generic.id, 'frame', 'window', { testOnly: true });
    assert.equal(store.records(generic.id).some(r => r.id === oldConversation.id), false);
    assert.deepEqual(store.context(generic.id).map(r => r.id), [oldConversation.id]);
    assert.equal(localAnswer('fleet', a).local, true);
    assert.match(localAnswer('fleet', a).summary, /확정할 수 없/);
    assert.doesNotMatch(localAnswer('setup', b).summary, /홉 섬/);
    const note = store.add(a.id, 'note', 'user', { text: '홉 공급 기억' });
    store.add(b.id, 'note', 'user', { text: '홉 다른 월드' });
    assert.equal(store.search(a.id, '홉').some(r => r.world_id === b.id), false);
    const frame = store.frame(a.id, Buffer.from('fixture-image'), { source: 'video', width: 1920, height: 1080, videoTime: 28 });
    assert.throws(() => store.evidence(b.id, frame.id));
    assert.throws(() => store.remove(b.id, note.id));
    const firstAnswer = store.add(a.id, 'answer', 'model', { summary: '예전 기억 기반', memory_refs: [note.id], evidence: [frame.id] });
    const secondAnswer = store.add(a.id, 'answer', 'model', { summary: '파생 기억', memory_refs: [firstAnswer.id] });
    store.amend(a.id, note.id, { text: '철판 정정 기억' }, true);
    assert.throws(() => store.record(a.id, firstAnswer.id));
    assert.throws(() => store.record(a.id, secondAnswer.id));
    assert.equal(store.search(a.id, '홉').some(r => r.id === note.id), false);
    assert.equal(store.search(a.id, '철판').some(r => r.id === note.id), true);
    store.update(a.id, { status: 'accepted', goal: '수정 목표', step: 3 });
    assert.equal(store.world(a.id).state.status, 'accepted');
    assert.throws(() => store.update(a.id, { status: 'resolved' }));
    assert.equal(store.world(a.id).state.status, 'accepted');
    const linked = store.add(a.id, 'answer', 'model', { summary: '삭제할 화면', evidence: [frame.id] });
    const file = store.evidence(a.id, frame.id).file;
    store.remove(a.id, frame.id);
    assert.equal(fs.existsSync(file), false);
    assert.throws(() => store.record(a.id, linked.id));
    assert.equal(store.search(a.id, '삭제할').length, 0);
    const old = store.frame(a.id, Buffer.from('old-image'), { source: 'window', width: 1, height: 1 });
    store.db.prepare('UPDATE records SET created_at=? WHERE id=?').run(new Date(Date.now() - 31 * 86400000).toISOString(), old.id);
    store.prune(); assert.throws(() => store.evidence(a.id, old.id));
    const usageId = store.reserveUsage('fixture-model', { status: 'sent' });
    store.updateUsage(usageId, { status: 'completed', usage: { cost: .001 } });
    store.db.prepare('DELETE FROM worlds WHERE id=?').run(b.id);
    assert.equal(store.usageSince('2000-01-01').length, 1);
    store.close(); store = openStore(directory);
    assert.equal(store.world(a.id).goal, '수정 목표');
    assert.equal(store.world(a.id).state.step, 3);
    assert.equal(store.usageSince('2000-01-01')[0].payload.usage.cost, .001);
    const providerFrame = { ...evidence[0], source: 'video', created_at: new Date().toISOString(), payload: { width: 1, height: 1, videoTime: 28 }, file: path.join(directory, 'fixture.jpg') };
    fs.writeFileSync(providerFrame.file, 'fixture-image');
    let sentBody, requests = 0;
    const parameters = { key: 'unit-test-key', model: 'fixture-model', world: a, question: '무역로?', evidence: [providerFrame], memories: [], signal: new AbortController().signal };
    const result = await analyze({ ...parameters, fetchImpl: async (url, options) => { requests++; assert.equal(url, 'https://openrouter.ai/api/v1/chat/completions'); sentBody = JSON.parse(options.body); return new Response(JSON.stringify({ choices: [{ message: { content: JSON.stringify(valid) } }], usage: { cost: .001 } })); } });
    assert.equal(result.answer.summary, '결론');
    assert.equal(sentBody.messages[1].content[1].type, 'image_url');
    assert.equal(JSON.parse(sentBody.messages[1].content[0].text).guide, null);
    await analyze({ ...parameters, world: {...a,state:{...a.state,scenario:'anno-hops',step:3}}, fetchImpl: async (_url, init) => { const context=JSON.parse(JSON.parse(init.body).messages[1].content[0].text); assert.equal(context.guide.current_step.number,4); assert.match(context.guide.current_step.title,/홉/); assert.match(context.guide.steps[1].items[0],/구매·판매/); assert.match(context.guide.steps[1].next,/단축키 T/); return new Response(JSON.stringify({choices:[{message:{content:JSON.stringify(valid)}}]})); } });
    const dialogueResult = await analyze({ ...parameters, recent, profile: { name: '두리', style: 'playful', tone: 'polite', preferences: '힌트만' }, mode: 'together', automatic: true, fetchImpl: async (_url, init) => { const body = JSON.parse(init.body), context = JSON.parse(body.messages[1].content[0].text); assert.equal(context.mode, 'together'); assert.equal(context.automatic, true); assert.deepEqual(context.conversation.map(r => r.reply), ['여기부터 볼까?', '좋았어!']); assert.equal(context.preferences, '힌트만'); assert.match(body.messages[0].content, /편한 존댓말/); return new Response(JSON.stringify({ choices: [{ message: { content: JSON.stringify({ ...valid, summary: '', should_speak: false, event_type: 'quiet' }) } }] })); } });
    assert.equal(dialogueResult.answer.should_speak, false);
    assert.equal(sentBody.response_format.type, 'json_schema');
    assert.equal(requests, 1);
    for (const status of [400, 401, 402, 429, 503]) await assert.rejects(analyze({ ...parameters, fetchImpl: async () => new Response('{}', { status }) }));
    let retries = 0;
    await assert.rejects(analyze({ ...parameters, fetchImpl: async () => { retries++; throw new DOMException('aborted', 'AbortError'); } }));
    assert.equal(retries, 1);
    await assert.rejects(analyze({ ...parameters, fetchImpl: async () => new Response(JSON.stringify({ choices: [{ message: { content: 'not JSON' } }] })) }));
    console.log('PASS: natural dialogue context, generic games, companion preferences, silence/freshness/focus/cooldown/deduplication, fleet boundaries, plan lifecycle, memory isolation/correction, SQLite restart, quota, provider validation/cancellation.');
    console.log('Provider responses above are fixtures; no paid API or actual game capture was tested.');
  } finally {
    store?.close();
    // Delete only the temporary directory created by this check, inside this workspace.
    assert.equal(path.dirname(path.resolve(directory)), local);
    assert.ok(path.basename(directory).startsWith('check-'));
    fs.rmSync(directory, { recursive: true, force: true });
  }
}
check().catch(error => { console.error(error); process.exitCode = 1; });
