const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { openStore } = require('../src/store.cjs');
const { validateAnswer, conversation } = require('../src/core.cjs');
const { analyze } = require('../src/provider.cjs');

module.exports = async function checkLearning() {
  const local = path.resolve(__dirname, '../.local');
  fs.mkdirSync(local, { recursive: true });
  const directory = fs.mkdtempSync(path.join(local, 'learning-check-'));
  let store = openStore(directory);
  try {
    const w = store.create('학습 시험', 'Factorio', '');
    const other = store.create('다른 세이브', 'Anno 1800', '');
    const before = store.frame(w.id, Buffer.from('fixture before'), { source: 'window', width: 1, height: 1, capturedAt: new Date().toISOString() });
    const decision = store.add(w.id, 'answer', 'model', { question: '남쪽섬은 관광용으로 남겨둘게', summary: '알겠어. 이 월드의 선택을 이어가자.', evidence: [before.id] });
    let prior = decision.id;
    for (let n = 0; n < 16; n++) prior = store.add(w.id, 'answer', 'model', { question: `새 대화 ${n}`, summary: `새 응답 ${n}`, memory_refs: [prior] }).id;
    const hidden = store.add(w.id, 'answer', 'model', { question: null, automatic: true, delivered: false, summary: '남쪽섬의 미전달 가설' });
    store.add(other.id, 'note', 'user', { text: '남쪽섬은 다른 세이브 소유' });
    assert.equal(conversation(store.context(w.id)).some(r => r.id === decision.id), false);
    let context = store.promptContext(w.id, '남쪽섬은 어떻게 하기로 했지?');
    const remembered = context.memories.find(r => r.id === decision.id);
    assert.equal(remembered.payload.question, '남쪽섬은 관광용으로 남겨둘게');
    assert.equal(remembered.payload.question_source, 'user');
    assert.equal(remembered.payload.reply_source, 'model');
    assert.equal(context.memories.some(r => r.id === hidden.id), false);
    assert.equal(context.memories.some(r => r.payload.text?.includes('다른 세이브')), false);

    const proposal = { title: '구리 공급 연결 확인', hypothesis: '공급 연결 때문에 멈췄을 가능성', action: '연결 한 구간을 바꿔보기', check: '다음 생산 주기에 공급과 가동 비교', conditions: '다른 요소는 그대로 두고 되돌릴 수 있게', evidence_ids: [before.id] };
    const answer = { summary: '이 연결부터 같이 확인해볼까?', should_speak: true, event_type: 'help', event_key: '구리:연결', focus_busy: false, goal_related: false, facts: [{ text: '화면 시험용 연결', evidence_id: before.id }], hypotheses: [proposal.hypothesis], missing_information: [], suggestions: [proposal.action], memory_proposals: [], next_action: proposal.action, annotations: [], learning_proposals: [proposal] };
    const checked = validateAnswer(answer, [before]);
    assert.equal(checked.learning_proposals.length, 1);
    assert.throws(() => validateAnswer({ ...answer, learning_proposals: [{ ...proposal, status: 'completed' }] }, [before]));
    assert.throws(() => validateAnswer({ ...answer, learning_proposals: [{ ...proposal, evidence_ids: ['foreign-frame'] }] }, [before]));
    assert.throws(() => validateAnswer({ ...answer, learning_proposals: [proposal, proposal, proposal] }, [before]));
    const saved = store.saveAnswer(w.id, 'model', { ...checked, question: '어떻게 바꾸면 좋을까?', evidence: [before.id] });
    let experience = store.record(w.id, saved.payload.experience_ids[0]);
    const experienceId = experience.id;
    assert.equal(experience.source, 'model');
    assert.equal(experience.payload.status, 'proposed');
    assert.equal(experience.payload.result, '');
    const repeated = store.saveAnswer(w.id, 'model', { ...checked, question: '다시 설명해줘', evidence: [before.id] });
    assert.equal(repeated.payload.experience_ids[0], experienceId);
    assert.equal(store.experiences(w.id).length, 1);
    const silent = store.saveAnswer(w.id, 'model', { ...checked, automatic: true, delivered: false });
    assert.deepEqual(silent.payload.experience_ids, []);
    const count = store.records(w.id, -1).length;
    assert.throws(() => store.saveAnswer(w.id, 'model', { ...answer, learning_proposals: [{ ...proposal, evidence_ids: ['not-found'] }] }));
    assert.equal(store.records(w.id, -1).length, count, 'A rejected proposal must roll back its answer too.');

    const change = patch => { experience = store.updateExperience(w.id, experienceId, { expected_revision: experience.payload.revision, ...patch }); return experience; };
    assert.throws(() => change({ status: 'completed', result: '모델이 성공 주장', outcome: 'improved' }));
    assert.equal(store.record(w.id, experienceId).payload.status, 'proposed');
    assert.throws(() => store.updateExperience(other.id, experienceId, { expected_revision: 1, status: 'accepted' }));
    change({ status: 'accepted' });
    assert.equal(experience.payload.result, '');
    assert.throws(() => change({ outcome: 'improved' }));
    assert.throws(() => store.updateExperience(w.id, experienceId, { expected_revision: 1, status: 'applied' }));
    const during = store.add(w.id, 'answer', 'model', { question: '우리 뭐 하기로 했지?', summary: '연결을 확인하기로 했어.', memory_refs: [experienceId] });
    change({ status: 'applied' });
    assert.equal(store.record(w.id, during.id).payload.question, '우리 뭐 하기로 했지?', 'Progress must preserve earlier conversation.');
    assert.throws(() => change({ status: 'completed', result: '' }));
    const after = store.frame(w.id, Buffer.from('fixture after'), { source: 'window', width: 1, height: 1, capturedAt: new Date().toISOString() });
    change({ status: 'completed', outcome: 'improved', result: '다음 생산 주기에 공급이 이어졌지만 소비 변화는 미확인', after_evidence: [after.id] });
    assert.equal(experience.payload.result_source, 'user');
    assert.deepEqual(experience.payload.before_evidence, [before.id]);
    assert.deepEqual(experience.payload.after_evidence, [after.id]);
    assert.equal(experience.payload.history.at(-1).source, 'user');
    assert.throws(() => change({ status: 'accepted' }));
    assert.throws(() => store.createExperience(other.id, proposal));

    for (let n = 0; n < 110; n++) store.frame(w.id, Buffer.from('newer fixture'), { source: 'window', width: 1, height: 1, capturedAt: new Date().toISOString() });
    const snapshot = store.snapshotRecords(w.id);
    assert.equal(store.records(w.id).some(r => r.id === before.id), false);
    assert.ok(snapshot.some(r => r.id === saved.id));
    assert.ok(snapshot.some(r => r.id === before.id));
    assert.ok(snapshot.some(r => r.id === after.id));
    context = store.analysisContext(w.id, '구리 공급 연결은 지난번에 효과 있었어?');
    assert.ok(context.memories.some(r => r.id === experienceId && r.payload.status === 'completed'));
    assert.ok(context.evidence.some(r => r.id === before.id));
    assert.equal(context.evidence.length, 2);
    assert.deepEqual(store.analysisContext(w.id, '이 화면', after.id).evidence.map(r => r.id), [after.id]);
    assert.throws(() => store.analysisContext(other.id, '다른 월드', before.id));

    const beforeFile = store.evidence(w.id, before.id).file;
    store.db.prepare('UPDATE records SET created_at=? WHERE id=?').run(new Date(Date.now() - 31 * 86400000).toISOString(), before.id);
    store.prune(); store.prune();
    assert.equal(fs.existsSync(beforeFile), false);
    assert.equal(store.record(w.id, before.id).payload.expired, true);
    assert.throws(() => store.evidence(w.id, before.id));
    assert.ok(store.record(w.id, decision.id));
    assert.ok(store.record(w.id, prior));
    assert.ok(store.record(w.id, saved.id));
    experience = store.record(w.id, experienceId);
    assert.equal(experience.payload.needs_review, true);
    context = store.analysisContext(w.id, '구리 공급');
    assert.deepEqual(context.memories.find(r => r.id === experienceId).unavailable_evidence, [before.id]);
    assert.equal(context.evidence.some(r => r.id === before.id), false);
    store.close(); store = openStore(directory);
    assert.equal(store.promptContext(w.id, '남쪽섬은 어떻게 했지?').memories.find(r => r.id === decision.id).payload.question_source, 'user');
    assert.equal(store.promptContext(w.id, '구리 공급').memories.find(r => r.id === experienceId).payload.result_source, 'user');

    let body;
    await analyze({ key: 'fixture-key', model: 'fixture-model', world: store.world(w.id), question: '구리 공급을 다시 보자', ...store.analysisContext(w.id, '구리 공급'), fetchImpl: async (_url, init) => {
      body = JSON.parse(init.body);
      const frameId = JSON.parse(body.messages[1].content[0].text).evidence[0].id;
      return new Response(JSON.stringify({ choices: [{ message: { content: JSON.stringify({ ...answer, facts: [{ text: 'fixture', evidence_id: frameId }], learning_proposals: [] }) } }] }));
    } });
    const sent = JSON.parse(body.messages[1].content[0].text);
    assert.ok(sent.memories.find(r => r.id === experienceId).payload.result.includes('미확인'));
    assert.ok(sent.memories.find(r => r.id === experienceId).time);
    assert.deepEqual(sent.memories.find(r => r.id === experienceId).unavailable_evidence, [before.id]);
    assert.match(body.messages[0].content, /공동 학습/);
    assert.match(body.messages[0].content, /한 번의 개선/);
    assert.equal(body.response_format.json_schema.schema.required.includes('learning_proposals'), true);

    const derived = store.add(w.id, 'answer', 'model', { summary: '지난 경험의 개선을 참고', memory_refs: [experienceId] });
    experience = store.record(w.id, experienceId);
    store.updateExperience(w.id, experienceId, { expected_revision: experience.payload.revision, result: '정정: 공급 회복은 다른 변경 때문일 수도 있어', outcome: 'inconclusive' });
    assert.throws(() => store.record(w.id, derived.id));
    assert.equal(store.promptContext(w.id, '구리 공급').memories.find(r => r.id === experienceId).payload.outcome, 'inconclusive');
    const linkedExperience = store.createExperience(w.id, { ...proposal, evidence_ids: [after.id] }, saved.id);
    const related = store.add(w.id, 'answer', 'model', { summary: '삭제할 경험 기반', memory_refs: [linkedExperience.id] });
    store.remove(w.id, after.id);
    assert.throws(() => store.record(w.id, experienceId));
    assert.throws(() => store.record(w.id, linkedExperience.id));
    assert.throws(() => store.record(w.id, related.id));
    assert.equal(store.promptContext(w.id, '구리').memories.some(r => r.id === experienceId), false);
    assert.ok(store.record(w.id, decision.id), 'Deleting an unrelated image must not delete the old user decision.');
    const waiting = store.createExperience(w.id, { ...proposal, evidence_ids: [] });
    const later = store.updateExperience(w.id, waiting.id, { expected_revision: 1, status: 'deferred' });
    const declined = store.updateExperience(w.id, waiting.id, { expected_revision: later.payload.revision, status: 'rejected' });
    assert.throws(() => store.updateExperience(w.id, waiting.id, { expected_revision: declined.payload.revision, status: 'applied' }));
    assert.equal(store.promptContext(w.id, '구리 공급 연결').memories.find(r => r.id === waiting.id).payload.status, 'rejected');
    const crowded = store.create('경험이 많은 플레이', 'Satisfactory', '');
    const oldest = store.createExperience(crowded.id, { ...proposal, evidence_ids: [] });
    for (let n = 0; n < 40; n++) store.createExperience(crowded.id, { ...proposal, action: `다른 시도 ${n}`, evidence_ids: [] });
    for (let n = 0; n < 120; n++) store.add(crowded.id, 'answer', 'model', { question: `최근 대화 ${n}`, summary: `최근 응답 ${n}` });
    assert.equal(store.experiences(crowded.id).some(r => r.id === oldest.id), false);
    const reused = store.saveAnswer(crowded.id, 'model', { summary: '기존 시도를 이어가자', question: '다시 보자', learning_proposals: [{ ...proposal, evidence_ids: [] }] });
    assert.equal(reused.payload.experience_ids[0], oldest.id);
    assert.ok(store.snapshotRecords(crowded.id).some(r => r.id === oldest.id));
    const currentCount = store.db.prepare("SELECT COUNT(*) AS n FROM records WHERE kind='frame' AND deleted_at IS NULL AND COALESCE(json_extract(payload,'$.expired'),0)=0").get().n;
    let last;
    for (let n = currentCount; n < 300; n++) last = store.frame(w.id, Buffer.from('limit fixture'), { source: 'window', width: 1, height: 1 });
    assert.throws(() => store.frame(w.id, Buffer.from('over limit'), { source: 'window' }), /보관 한도/);
    store.db.prepare('UPDATE records SET created_at=? WHERE id=?').run(new Date(Date.now() - 31 * 86400000).toISOString(), last.id);
    store.prune();
    assert.ok(store.frame(w.id, Buffer.from('released slot'), { source: 'window', width: 1, height: 1 }));
    console.log('PASS: long-term retrieval, retained image references, expiry without conversation loss, experience lifecycle/reuse, correction/deletion, rollback, world isolation and structured learning context.');
  } finally {
    store.close();
    assert.equal(path.dirname(directory), local);
    fs.rmSync(directory, { recursive: true, force: true });
  }
};
